CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS schools(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, address text, contact text, email text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id) ON DELETE CASCADE, username text NOT NULL, password_hash text NOT NULL, full_name text NOT NULL, role text NOT NULL CHECK(role IN ('OWNER','ADMIN','ACCOUNTANT','TEACHER','LIBRARIAN','STOREKEEPER','VIEWER')), active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(school_id,username));
CREATE TABLE IF NOT EXISTS students(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id) ON DELETE CASCADE, admission_no text NOT NULL, first_name text NOT NULL, middle_name text, last_name text, dob date, gender text, class_name text, admission_date date, hometown text, religion text, mother_tongue text, father text, mother text, contact_numbers text, emergency_contact text, occupation text, address text, photo_url text, status text NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','TRANSFERRED','RUSTICATED','GRADUATED')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(school_id,admission_no));
CREATE TABLE IF NOT EXISTS fee_schedules(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id) ON DELETE CASCADE, class_name text NOT NULL, term1 numeric(12,2) NOT NULL DEFAULT 0, term2 numeric(12,2) NOT NULL DEFAULT 0, term3 numeric(12,2) NOT NULL DEFAULT 0, UNIQUE(school_id,class_name));
CREATE TABLE IF NOT EXISTS payments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id) ON DELETE CASCADE, student_id uuid NOT NULL REFERENCES students(id) ON DELETE CASCADE, receipt_no text NOT NULL, payment_date date NOT NULL, amount numeric(12,2) NOT NULL CHECK(amount>=0), school_fees numeric(12,2) NOT NULL DEFAULT 0, other_fees numeric(12,2) NOT NULL DEFAULT 0, method text, note text, created_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(school_id,receipt_no));
CREATE TABLE IF NOT EXISTS scholarships(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id) ON DELETE CASCADE, student_id uuid NOT NULL REFERENCES students(id) ON DELETE CASCADE, award_date date NOT NULL, purpose text, amount numeric(12,2) NOT NULL CHECK(amount>=0), created_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS alumni(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id) ON DELETE CASCADE, admission_no text, student_name text, designation text, contact text, graduation_year int, arrears numeric(12,2) DEFAULT 0, paid numeric(12,2) DEFAULT 0, balance numeric(12,2) DEFAULT 0);
CREATE TABLE IF NOT EXISTS library_loans(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id) ON DELETE CASCADE, student_id uuid REFERENCES students(id), book_title text NOT NULL, book_number text, borrow_date date, due_date date, return_date date, remark text);
CREATE TABLE IF NOT EXISTS products(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id) ON DELETE CASCADE, product_code text NOT NULL, details text, unit text, category text, reorder_level numeric(12,2) DEFAULT 0, opening_stock numeric(12,2) DEFAULT 0, UNIQUE(school_id,product_code));
CREATE TABLE IF NOT EXISTS inventory_movements(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id) ON DELETE CASCADE, product_id uuid NOT NULL REFERENCES products(id) ON DELETE CASCADE, movement_date date NOT NULL, invoice_number text, details text, received numeric(12,2) DEFAULT 0, issued numeric(12,2) DEFAULT 0, created_by uuid REFERENCES users(id));
CREATE TABLE IF NOT EXISTS audit_log(id bigserial PRIMARY KEY, school_id uuid REFERENCES schools(id) ON DELETE CASCADE, user_id uuid REFERENCES users(id), action text NOT NULL, entity text, entity_id uuid, metadata jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS students_search_idx ON students(school_id,class_name,status);
CREATE INDEX IF NOT EXISTS payments_student_idx ON payments(school_id,student_id,payment_date);
CREATE INDEX IF NOT EXISTS audit_school_idx ON audit_log(school_id,created_at DESC);

CREATE TABLE IF NOT EXISTS import_runs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), file_hash text NOT NULL UNIQUE, source_name text NOT NULL, imported_at timestamptz NOT NULL DEFAULT now());
