import 'dotenv/config'; import XLSX from 'xlsx'; import pg from 'pg'; import bcrypt from 'bcryptjs'; import fs from 'fs'; import crypto from 'crypto';
const {Pool}=pg; const useSSL=process.env.DATABASE_SSL==='true' || process.env.DATABASE_URL?.includes('sslmode=require'); const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:useSSL?{rejectUnauthorized:false}:undefined});
const file=process.argv[2]||'DIGI-SCHOOL (WGIS)-3new(1).xlsm'; if(!fs.existsSync(file)) throw Error(`Workbook not found: ${file}`); const fileHash=crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const wb=XLSX.readFile(file,{cellDates:true}); const rows=name=>XLSX.utils.sheet_to_json(wb.Sheets[name]||{}, {defval:null});
const clean=v=>v instanceof Date?v.toISOString().slice(0,10):v;
const first=(o,...keys)=>{for(const k of keys) if(o[k]!==undefined&&o[k]!==null&&o[k]!=='') return clean(o[k]); return null};
const q=async(t,p=[])=>{const c=await pool.connect();try{return (await c.query(t,p)).rows}finally{c.release()}};
async function main(){
 const existing=await q('select id from import_runs where file_hash=$1',[fileHash]); if(existing.length){console.log('This workbook has already been imported; nothing to do.'); return;}
 await q('begin'); try{
 let [school]=await q('select id from schools limit 1'); if(!school)[school]=await q('insert into schools(name,address,contact,email) values($1,$2,$3,$4) returning id',[process.env.SCHOOL_NAME||'Wisdom Gate International School','BOX 53, NAVRONGO','0247443733/0200631993','elijahkandwe@gmail.com']);
 const schoolId=school.id;
 const adminRows=rows('ADMIN'); const adminUser=first(adminRows[0]||{},'USER ID','USER','USERNAME')||'ADMIN'; const adminPass=process.env.ADMIN_PASSWORD||first(adminRows[0]||{},'PASSWORD')||'BANTUS';
 await q('insert into users(school_id,username,password_hash,full_name,role) values($1,$2,$3,$4,$5) on conflict(school_id,username) do nothing',[schoolId,adminUser,await bcrypt.hash(adminPass,12),'School Administrator','OWNER']);
 for(const r of rows('DATABASE')){const id=first(r,'ID NUMBER'); if(!id) continue; await q(`insert into students(school_id,admission_no,first_name,middle_name,last_name,dob,gender,class_name,admission_date,hometown,religion,mother_tongue,father,mother,contact_numbers,emergency_contact,occupation,address) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18) on conflict(school_id,admission_no) do update set first_name=excluded.first_name,middle_name=excluded.middle_name,last_name=excluded.last_name,class_name=excluded.class_name,status='ACTIVE'`,[schoolId,id,first(r,'STUDENT NAME','FIRST NAME')||'Unknown',first(r,'MIDDLE NAME'),first(r,'LAST NAME'),first(r,'DOB','DATE OF BIRTH'),first(r,'GENDER'),first(r,'CLASS'),first(r,'DATE OF ADMISSION'),first(r,'HOMETOWN'),first(r,'RELIGION'),first(r,"MOTHER'S TONGUE",'MOTHER TONGUE'),first(r,'FATHER'),first(r,'MOTHER'),first(r,'CONTACT NUMBERS','CONTACT'),first(r,'EMERGENCY CONTACT'),first(r,'OCCUPATION'),first(r,'ADDRESS')]);}
 for(const r of rows('FEES')){const c=first(r,'CLASS','CLASS/LEVEL','CLASS / LEVEL');if(!c||String(c).toUpperCase()==='START')continue;await q(`insert into fee_schedules(school_id,class_name,term1,term2,term3) values($1,$2,$3,$4,$5) on conflict(school_id,class_name) do update set term1=excluded.term1,term2=excluded.term2,term3=excluded.term3`,[schoolId,c,Number(first(r,'TERM ONE','TERM 1')||0),Number(first(r,'TERM TWO','TERM 2')||0),Number(first(r,'TERM THREE','TERM 3')||0)]);}
 const students=await q('select id,admission_no from students where school_id=$1',[schoolId]); const map=new Map(students.map(x=>[x.admission_no,x.id]));
 for(const r of rows('PAYMENT')){const id=first(r,'ID NUMBER'),sid=map.get(id);if(!sid)continue;const receipt=first(r,'RECEIPT NUMBER','RECEIPT NO');if(!receipt)continue;await q(`insert into payments(school_id,student_id,receipt_no,payment_date,amount,school_fees,other_fees) values($1,$2,$3,$4,$5,$6,$7) on conflict(school_id,receipt_no) do nothing`,[schoolId,sid,receipt,first(r,'DATE')||new Date().toISOString().slice(0,10),Number(first(r,'AMOUNT')||0),Number(first(r,'SCHOOL FEES')||0),Number(first(r,'OTHER FEES')||0)]);}
 for(const r of rows('SCHOLARSHIP')){const sid=map.get(first(r,'STUDENT ID','ID NUMBER'));if(!sid)continue;await q(`insert into scholarships(school_id,student_id,award_date,purpose,amount) values($1,$2,$3,$4,$5)`,[schoolId,sid,first(r,'DATE')||new Date().toISOString().slice(0,10),first(r,'PURPOSE'),Number(first(r,'AMOUNT')||0)]);}
 await q('insert into import_runs(file_hash,source_name) values($1,$2)',[fileHash,file]); await q('commit'); console.log('Seed complete. School:',schoolId,'Admin:',adminUser); }catch(e){await q('rollback');throw e}}
main().finally(()=>pool.end());
